[package]
name = "craprs"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2", features = ["full", "visit"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
